import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { products } from "../data/data.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1>Products</h1>
        {products.map((product) => {
          return <div>{product.title}</div>;
        })}
      </div>
    </div>
  );
}
