import Head from "next/head";
import Image from "next/image";
import Link from "next/link.js";
import { products } from "../../data/data.js";

const Home = () => {
	return (
		<div>
			<Head>
				<title>Products</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>
				<h1>Products</h1>
				<table className="tablt">
					<thead>
						<tr>
							<th> Title</th>
							<th> Image</th>
							<th> Price</th>
							<th> Category </th>
						</tr>
					</thead>
					{products.map((product) => {
						return (
							<>
								<tr key={product.id}>
									<td>
										<Link href={{pathname:'products/[id]', query: { id: product.id}}}>
											<a>{product.title}</a>
										</Link>
									</td>
									<td>
										<Image
											src={product.image}
											alt="product Image"
											width="100vw"
											height="100vw"
										/>
									</td>
									<td>{product.price}</td>
									<td>{product.category}</td>
								</tr>
							</>
						);
					})}
				</table>
			</div>
		</div>
	);
}
export default Home;
